# Generated by Django 5.0.1 on 2024-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_record',
            name='others',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
