# Generated by Django 5.0.6 on 2024-11-10 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_record',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.client'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.component'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.department'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
