# Generated by Django 5.0.6 on 2024-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0002_statistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
