# Generated by Django 5.0.6 on 2024-11-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0002_alter_staff_record_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff_record',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.client'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.component'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiving_app.department'),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_record',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
