# Generated by Django 5.0.6 on 2024-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0003_alter_statistics_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200, null=True)),
                ('count', models.IntegerField(null=True)),
                ('date_component', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
