# Generated by Django 5.0.6 on 2024-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving_app', '0004_component_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_record',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
